# Generated by Django 3.0.4 on 2020-03-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblyline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assemblyline',
            table='al_assembly_line',
        ),
        migrations.AlterModelTable(
            name='compoundmachine',
            table='al_compound_machine',
        ),
        migrations.AlterModelTable(
            name='machinegroup',
            table='al_machine_group',
        ),
    ]
