# Generated by Django 3.0.4 on 2020-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblyline', '0002_auto_20200323_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblylinecompoundmachine',
            name='postion',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='assemblylinemachine',
            name='postion',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
