# Generated by Django 3.0.4 on 2020-03-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblyline', '0003_auto_20200323_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_params', models.TextField(blank=True)),
                ('output_params', models.TextField(blank=True)),
                ('assembly_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assemblyline.AssemblyLine')),
            ],
            options={
                'db_table': 'al_product_line',
            },
        ),
        migrations.CreateModel(
            name='ProductLineMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion', models.PositiveSmallIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblyline.Machine')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblyline.ProductLine')),
            ],
            options={
                'db_table': 'al_product_line_machine',
            },
        ),
        migrations.AddField(
            model_name='productline',
            name='machies',
            field=models.ManyToManyField(related_name='_productline_machies_+', through='assemblyline.ProductLineMachine', to='assemblyline.Machine'),
        ),
    ]
