# Generated by Django 3.0.4 on 2020-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblyline', '0004_auto_20200323_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='engine',
            new_name='engine_type',
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='product_model',
            field=models.CharField(default='merge', max_length=20),
        ),
    ]
