# Generated by Django 3.0.4 on 2020-03-26 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemblyline', '0005_auto_20200325_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imput_params', models.TextField(blank=True)),
                ('output_params', models.TextField(blank=True)),
                ('assembly_line_name', models.CharField(default='产品线名称', max_length=200)),
                ('product', models.TextField(blank=True)),
                ('last_subproduct_id', models.BigIntegerField()),
                ('status', models.CharField(default='progressing', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assembly_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assemblyline.AssemblyLine')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'al_product_record',
            },
        ),
        migrations.RemoveField(
            model_name='productline',
            name='machies',
        ),
        migrations.AddField(
            model_name='productline',
            name='machines',
            field=models.ManyToManyField(related_name='_productline_machines_+', through='assemblyline.ProductLineMachine', to='assemblyline.Machine'),
        ),
        migrations.CreateModel(
            name='SubProducrRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imput_params', models.TextField(blank=True)),
                ('output_params', models.TextField(blank=True)),
                ('product', models.TextField(blank=True)),
                ('status', models.CharField(default='progressing', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assemblyline.Machine')),
                ('product_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblyline.ProductRecord')),
            ],
            options={
                'db_table': 'al_sub_product_record',
            },
        ),
        migrations.AddField(
            model_name='productrecord',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assemblyline.ProductLine'),
        ),
    ]
